export const POST_QUERY_OPTIONS = {
  searchableFields: ["title", "content", "locationName", "country"],
  filterableFields: [
    "author",
    "category",
    "country",
    "locationName",
    "travelDays",
    "estimatedCost",
    "travelType",
    "premium",
  ],
  sortableFields: [
    "createdAt",
    "updatedAt",
    "upvoteCount",
    "downvoteCount",
    "estimatedCost",
    "travelDays",
  ],
  selectableFields: [
    "title",
    "category",
    "locationName",
    "country",
    "travelDays",
    "estimatedCost",
    "travelType",
    "image",
    "premium",
    "upvoteCount",
    "downvoteCount",
    "createdAt",
  ],
};
