export const USER_QUERY_OPTIONS = {
  searchableFields: ["name", "email", "address"],
  filterableFields: [
    "email",
    "age",
    "gender",
    "address",
    "role",
    "status",
    "isVerified",
    "premiumAccess",
    "isDeleted",
  ],
  sortableFields: [
    "name",
    "age",
    "email",
    "followerCount",
    "followingCount",
    "createdAt",
    "updatedAt",
  ],
  selectableFields: [
    "name",
    "email",
    "age",
    "gender",
    "address",
    "role",
    "status",
    "isVerified",
    "premiumAccess",
  ],
};
