export const TRAVELPLAN_QUERY_OPTIONS = {
  searchableFields: ["startLocation", "destination", "note"],
  filterableFields: [
    "user",
    "startLocation",
    "destination",
    "startDate",
    "endDate",
    "travelDays",
    "minBudget",
    "maxBudget",
    "status",
  ],
  sortableFields: [
    "createdAt",
    "updatedAt",
    "startDate",
    "travelDays",
    "minBudget",
    "maxBudget",
  ],
  selectableFields: [
    "user",
    "startLocation",
    "destination",
    "startDate",
    "endDate",
    "travelDays",
    "minBudget",
    "maxBudget",
    "contact",
    "note",
    "status",
  ],
};
